- name: Install MongoDB on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: install 1/
      shell: sudo apt-get install gnupg
    - name: install 2/
      shell: wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
    - name: install 3/
      shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
    - name: insatll 4/
      shell: sudo apt-get update
    - name: install 5/
      shell: sudo apt-get install -y mongodb-org
    - name: Stop
      shell: sudo systemctl stop mongod
    - name: Abrir las ip
      lineinfile:
        path: /etc/mongod.conf
        regexp: 'bindIp: 127.0.0.1'
        line: '  bindIp: 52.91.151.69,3.238.33.52'
    - name: Start
      shell: sudo systemctl start mongod
