- name: Install MongoDB on Ubuntu
  hosts: all
  become: yes

  tasks:
    - name: Install gnupg
      shell: sudo apt-get install gnupg
    - name: Extraer la key
      shell: wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key ad$
    - name: Traer repositorio
      shell: echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongo$
    - name: Actualizar packetes
      shell: sudo apt-get update
    - name: Install mongo
      shell: sudo apt-get install -y mongodb-org
    - name: Iniciar mongo db
      shell: sudo systemctl start mongod
    - name: Abrir las ip
      lineinfile:
        path: /etc/mongod.conf
        regexp: 'bindIp: 127.0.0.1'
        line: '  bindIp: 0.0.0.1,0.0.0.2'
